version: '2.2'

services:
  cassandra:
    image: cassandra:3.11.2
    container_name: cassandra
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "9042:9042"
      - "9160:9160"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    restart: always
#    volumes:
#      - ./volumes/cassandra/cassandra_data:/var/lib/cassandra
    healthcheck:
      test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10

  cassandra-load-keyspace:
    container_name: cassandra-load-keyspace
    image: cassandra:3.11.2
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      #      - ./volumes/cassandra/cassandra_schema.cql:/cql/schema.cql
      - ./volumes/cassandra/cassandra_schemas/:/cql/
    command: /bin/bash -c "echo loading cassandra keyspace && cqlsh cassandra -f /cql/killrvideos.cql; cqlsh cassandra -f /cql/killrvideos_inserts.cql"

  cassandra-web:
    image: ipushc/cassandra-web
    environment:
      - "CASSANDRA_HOST=cassandra"
      - "CASSANDRA_PORT=9042"
      - "HOST_PORT:80"
    #      - "CASSANDRA_BROADCAST_ADDRESS=cassandra"
    #      - "CASSANDRA_USERNAME=cassandra"
    #      - "CASSANDRA_PASSWORD=cassandra"
    restart: always
    depends_on:
      - "cassandra"
    ports:
      - "8092:8083"